# -*- coding: utf-8 -*-
"""1BF24CS302_Week2_DFS_IDS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSMB5GSSSbe6QFql-luV-3vbWH_ud-RF
"""

#dfs
import copy
goal_state = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
]

initial_state = [
    [1, 2, 3],
    [4, 0, 5],
    [7, 8, 6]
]

def matrix_to_tuple(matrix):

    return tuple(tuple(row) for row in matrix)

def print_board(matrix):

    for row in matrix:
        print(" ".join(str(x) if x != 0 else "_" for x in row))
    print("-" * 7)

def dfs(current_state, path, visited, depth, limit):

    if current_state == goal_state:
        print("Goal reached!\n")
        print(f"--- Solution Found in {len(path) - 1} Moves ---")
        for step, state in enumerate(path):
            print(f"Move {step}:")
            print_board(state)
        return True


    if depth >= limit:
        return False

    blank_row, blank_col = -1, -1
    for r in range(3):
        for c in range(3):
            if current_state[r][c] == 0:
                blank_row, blank_col = r, c
                break

    possible_moves = []
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for dr, dc in directions:
        new_r, new_c = blank_row + dr, blank_col + dc

        if 0 <= new_r < 3 and 0 <= new_c < 3:
            possible_moves.append((new_r, new_c))


    for new_r, new_c in possible_moves:

        new_state = copy.deepcopy(current_state)

        new_state[blank_row][blank_col], new_state[new_r][new_c] = new_state[new_r][new_c], new_state[blank_row][blank_col]

        state_tuple = matrix_to_tuple(new_state)


        if state_tuple not in visited:
            visited.add(state_tuple)
            path.append(new_state)

            if dfs(new_state, path, visited, depth + 1, limit):
                return True

            path.pop()
            visited.remove(state_tuple)

    return False

print("Initial Board Layout:")
print_board(initial_state)

path_tracker = [initial_state]
visited_tracker = {matrix_to_tuple(initial_state)}

max_depth_limit = 10
solution_found = dfs(initial_state, path_tracker, visited_tracker, 0, max_depth_limit)

if not solution_found:
    print("No solution found within the specified move limit.")

#idfs
import copy

goal_state = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
]

initial_state = [
    [1, 2, 3],
    [4, 0, 5],
    [7, 8, 6]
]


def print_board(matrix):

    for row in matrix:
        print(" ".join(str(x) if x != 0 else "_" for x in row))
    print("-" * 7)

def depth_limited_dfs(current_state, path, current_limit):

    if current_state == goal_state:
        print("Goal reached!")
        print(f"Solution found at depth limit: {len(path) - 1}")
        print("\n--- Solution Path ---")
        for step, state in enumerate(path):
            print(f"Move {step}:")
            print_board(state)
        return True


    if current_limit <= 0:
        return False

    blank_row, blank_col = -1, -1
    for r in range(3):
        for c in range(3):
            if current_state[r][c] == 0:
                blank_row, blank_col = r, c
                break

    possible_moves = []
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    for dr, dc in directions:
        new_r, new_c = blank_row + dr, blank_col + dc
        if 0 <= new_r < 3 and 0 <= new_c < 3:
            possible_moves.append((new_r, new_c))


    for new_r, new_c in possible_moves:

        new_state = copy.deepcopy(current_state)
        new_state[blank_row][blank_col], new_state[new_r][new_c] = new_state[new_r][new_c], new_state[blank_row][blank_col]

        if new_state not in path:
            path.append(new_state)

            if depth_limited_dfs(new_state, path, current_limit - 1):
                return True

            path.pop()

    return False


def iterative_deepening_search(initial_state):
    print("Initial Board Layout:")
    print_board(initial_state)

    depth = 0
    max_allowable_depth = 50


    while depth <= max_allowable_depth:
        print(f"Searching at depth limit: {depth}...")
        path = [initial_state]


        if depth_limited_dfs(initial_state, path, depth):
            return True

        depth += 1

    print("No solution found within maximum depth limit.")
    return False

iterative_deepening_search(initial_state)