# -*- coding: utf-8 -*-
"""1BF24CS302_Week3_A*_MisplacedTiles_A*_ManhattanDistance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A897n3qTHWiHcYnlCWMpq5ucz4M5JBCG
"""

#MISPLACED
import heapq

initial = (
    (2, 8, 3),
    (1, 6, 4),
    (7, 5, 0)
)

goal = (
    (1, 2, 3),
    (8, 0, 4),
    (7, 6, 5)
)

def misplaced_tiles(matrix):
    count = 0
    for r in range(3):
        for c in range(3):
            val = matrix[r][c]
            if val != 0 and val != goal[r][c]:
                count += 1
    return count

def get_neighbors(matrix):
    neighbors = []

    blank_r, blank_c = 0, 0
    for r in range(3):
        for c in range(3):
            if matrix[r][c] == 0:
                blank_r, blank_c = r, c
                break

    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for dr, dc in moves:
        new_r = blank_r + dr
        new_c = blank_c + dc

        if 0 <= new_r < 3 and 0 <= new_c < 3:

            new_matrix = [list(row) for row in matrix]

            new_matrix[blank_r][blank_c], new_matrix[new_r][new_c] = \
                new_matrix[new_r][new_c], new_matrix[blank_r][blank_c]

            neighbors.append(tuple(tuple(row) for row in new_matrix))

    return neighbors

def a_star():

    open_list = []
    h = misplaced_tiles(initial)
    heapq.heappush(open_list, (h, 0, initial, [initial]))

    best_g = {initial: 0}

    while open_list:
        f, g, matrix, path = heapq.heappop(open_list)

        if matrix == goal:
            return path

        for next_matrix in get_neighbors(matrix):
            new_g = g + 1

            if next_matrix not in best_g or new_g < best_g[next_matrix]:
                best_g[next_matrix] = new_g
                h = misplaced_tiles(next_matrix)
                new_f = new_g + h
                heapq.heappush(
                    open_list,
                    (new_f, new_g, next_matrix, path + [next_matrix])
                )

    return None

solution = a_star()
if solution:
    print("Solution found!")
    print("Number of moves:", len(solution) - 1)

    for i, matrix in enumerate(solution):
        h = misplaced_tiles(matrix)
        g = i
        f = g + h

        print(f"\nStep {i} ——— g(n)={g}, h(n)={h}, f(n)={f}")
        for row in matrix:
            print(f"{row[0]}  {row[1]}  {row[2]}")
else:
    print("No solution found.")

#MANHATTAN
import heapq

initial = (2, 8, 3, 1, 6, 4, 7, 5, 0)
goal = (1, 2, 3, 8, 0, 4, 7, 6, 5)

def manhattan_distance(state):
    distance = 0
    for i in range(9):
        if state[i] != 0:
            current_row = i // 3
            current_col = i % 3
            goal_position = goal.index(state[i])
            goal_row = goal_position // 3
            goal_col = goal_position % 3
            distance += abs(current_row - goal_row) + abs(current_col - goal_col)
    return distance

def get_neighbors(state):
    neighbors = []
    blank = state.index(0)
    row = blank // 3
    col = blank % 3
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    for dr, dc in moves:
        new_row = row + dr
        new_col = col + dc
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_blank = new_row * 3 + new_col
            new_state = list(state)
            new_state[blank], new_state[new_blank] = new_state[new_blank], new_state[blank]
            neighbors.append(tuple(new_state))
    return neighbors

def a_star():
    open_list = []
    h = manhattan_distance(initial)
    heapq.heappush(open_list, (h, 0, initial, [initial]))
    best_g = {initial: 0}
    while open_list:
        f, g, state, path = heapq.heappop(open_list)
        if state == goal:
            return path
        for next_state in get_neighbors(state):
            new_g = g + 1
            if next_state not in best_g or new_g < best_g[next_state]:
                best_g[next_state] = new_g
                h = manhattan_distance(next_state)
                new_f = new_g + h
                heapq.heappush(open_list, (new_f, new_g, next_state, path + [next_state]))
    return None

solution = a_star()
for i, state in enumerate(solution):
    h = manhattan_distance(state)
    g = i
    f = g + h
    print(f"Step {i}: g={g}, h={h}, f={f}")
    for j in range(0, 9, 3):
        print(f"  {state[j]} {state[j+1]} {state[j+2]}")